apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: sre-chaos
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: default # Ensure Prometheus has RBAC permissions
      containers:
      - name: prometheus
        image: prom/prometheus:v2.30.3 # Using public Prometheus image
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--web.enable-lifecycle"
        ports:
          - containerPort: 9090
        volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus/
          - name: prometheus-rules-volume
            mountPath: /etc/prometheus/rules
          - name: prometheus-storage-volume
            mountPath: /prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: prometheus-rules-volume
          configMap:
            name: prometheus-rules-kube-state-metrics
        - name: prometheus-storage-volume
          emptyDir: {} # For persistent storage, use a PVC
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: sre-chaos
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP