apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: sre-chaos
type: Opaque
stringData:
  DB_HOST: backend-db # Name of the PostgreSQL service in Kubernetes
  DB_USER: user
  DB_PASSWORD: password
  DB_NAME: sre_challenge_db
