apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sre-chaos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/artful-winter-473414-q1/sre-chaos-challenge-backend:latest
        ports:
        - containerPort: 3001

